---
# tasks file for avocado-install
- name: Avocado-FrameWork Remove 
  hosts: rhel_machine
  user: vagrant
  become: yes
  tasks:
  - block:
      - debug: msg='Step 1 Removing Avocado-Framework Exists'
      - command: 'avocado --version' 
        ignore_errors: yes    
      - debug: msg='All set Avocado is already here'
    rescue:
      - debug: msg='Installing Avocado ... '
      - yum: name=avocado state=absent 
      - debug: msg='Done with deletion...'
        ignore_errors: yes    
        tags:
           - rhel
    always:
      - debug: msg="this always executes"
      - yum: name=avocado state=absent 

  - block:
      - debug: msg='Step 2 Verification Python - Pip  removed'
      - command: 'pip --version'
      - debug: msg='All set python-pip is already here!!'
        ignore_errors: yes
    rescue:
      - debug: msg='Step 2 Verification Python - Pip  removed'
    always:
      - debug: msg="this always executes"
      - yum: name=python-pip state=absent


  - block:
      - debug: msg='Step 3 Verification Python-vagrant library removed'
      - command: 'python -c "import vagrant"'
      - debug: msg='All set python-vagrant is already here!!'
        ignore_errors: yes    
    rescue:
      - debug: msg='removing python-vagrant ... '
      - command: "pip uninstall python-vagrant"
      - debug: msg='Done with uninstallation...'
        ignore_errors: yes    
        tags:
           - rhel
    always:
      - debug: msg="this always executes"
      - command: "pip uninstall python-vagrant"

  - block:
      - debug: msg='Step 4 Verification Python-Pexpect Absent'
      - command: 'python -c "import pexpect"'
      - debug: msg='All set python-vagrant is already here!!'
        ignore_errors: yes
    rescue:
      - debug: msg='UnInstalling python-pexpect ... '
      - command: "pip uninstall pexpect"
      - debug: msg='Done with uninstallation...'
        ignore_errors: yes 
        tags:
           - rhel
    always:
      - debug: msg="this always executes"
      - command: "pip uninstall pexpect"


  - block:
      - debug: msg='Step 4 Verification Git Exists'
      - command: 'git --version'
      - debug: msg='All set git is already here!!'
        ignore_errors: yes
    rescue:
      - debug: msg='unInstalling git ... '
      - yum: name=git state=absent
      - debug: msg='Done with uninstallation...'
        ignore_errors: yes
        tags:
           - rhel
    always:
      - debug: msg="this always executes"
      - yum: name=git state=absent


  - block:
      - debug: msg='Step 5 Clonning github test project'
      - debug: msg='All set git clone is already here!!'
        ignore_errors: yes
    rescue:
      - debug: msg='Removing project'
      - command: "rm -rf /home/vagrant/cdk-test"
      - debug: msg='Done with Deletion...'
        ignore_errors: yes
        tags:
           - rhel
    always:
      - debug: msg="this always executes"
      - command: "rm -rf /home/vagrant/cdk-test"

